# Can't be connected via url
# Credentials are shown below

version: '3'

services:
  dynamodb:
    container_name: dynamodb-template
    command: -sharedDb
    image: dwmkerr/dynamodb:latest
    restart: always
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: 1
      AWS_SECRET_ACCESS_KEY: 1
    ports:
      - '8000:8000'
    volumes:
      - ./.data/dynamodb:/dynamodb_local_db
    networks:
      - dynamodb-connect

networks:
  dynamodb-connect:
    driver: bridge
